In [1]:
import numpy as np

In [2]:
5/2

2.5

In [6]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [7]:
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [8]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
arr1^2

array([[ 3,  0,  1,  6],
       [10, 11,  8,  9]])