In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# Universal functions are basic functions that can be applied to every value in an array
np.sqrt(arr) # Square root of every value in array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
A = np.random.randn(10) # Random normal distriubtion
A

array([-0.31487191,  1.16232144, -0.37982921,  0.49933093, -0.47410817,
       -0.22061963, -0.32381796, -0.15704129,  0.48814798, -0.38896153])

In [6]:
B = np.random.randn(10)
B

array([-0.67215174,  0.6686401 , -0.69109402, -0.81525986,  1.41611066,
       -1.15446834, -1.19921662,  0.69355905, -2.01815583, -0.25508186])

In [7]:
np.add(A,B)

array([-0.98702366,  1.83096155, -1.07092324, -0.31592894,  0.94200249,
       -1.37508797, -1.52303458,  0.53651776, -1.53000785, -0.64404339])

In [8]:
np.maximum(A,B)

array([-0.31487191,  1.16232144, -0.37982921,  0.49933093,  1.41611066,
       -0.22061963, -0.32381796,  0.69355905,  0.48814798, -0.25508186])

In [12]:
# For list of all universal functions
import webbrowser
url = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
webbrowser.open(url)

True