In [1]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd
from numpy.random import randn

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['x','y'])
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

x    3
y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
x    3
y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1,sort=False)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
x  NaN  3.0
y  NaN  4.0

In [12]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  x    3
      y    4
dtype: int64

In [13]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['x','y','z'])
dframe2 = DataFrame(np.random.randn(3,3), columns=['y','q','x'])

In [14]:
dframe1

x         y         z
0  0.331205 -0.660561  0.804423
1 -2.621946  2.175393 -0.592153
2  0.007742  0.401784  1.500576
3  0.372371  0.132807  1.759244

In [15]:
dframe2

y         q         x
0  0.941558 -0.724850  0.200988
1  0.334192  0.595734 -0.635052
2  1.261173 -1.832340 -0.300303

In [19]:
pd.concat([dframe1,dframe2],sort=True)

q         x         y         z
0       NaN  0.331205 -0.660561  0.804423
1       NaN -2.621946  2.175393 -0.592153
2       NaN  0.007742  0.401784  1.500576
3       NaN  0.372371  0.132807  1.759244
0 -0.724850  0.200988  0.941558       NaN
1  0.595734 -0.635052  0.334192       NaN
2 -1.832340 -0.300303  1.261173       NaN

In [22]:
pd.concat([dframe1, dframe2], ignore_index=True,sort=True)

q         x         y         z
0       NaN  0.331205 -0.660561  0.804423
1       NaN -2.621946  2.175393 -0.592153
2       NaN  0.007742  0.401784  1.500576
3       NaN  0.372371  0.132807  1.759244
4 -0.724850  0.200988  0.941558       NaN
5  0.595734 -0.635052  0.334192       NaN
6 -1.832340 -0.300303  1.261173       NaN