In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arrz)

NameError: name 'arrz' is not defined

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [7]:
A = np.random.randn(10)

In [8]:
A

array([-0.16520226,  0.88197108,  2.30415429,  0.50115688, -0.68092224,
        0.81375717, -0.13006486, -1.22886937, -0.13446684,  0.60980092])

In [9]:
B = np.random.randn(10)
B

array([ 0.67662148, -1.01676667, -0.68494795, -0.35302436, -0.01192275,
        0.0161064 , -0.18153279, -0.07711241, -1.63665266, -0.68396572])

In [10]:
# Binary Fuctions
np.add(A,B)

array([ 0.51141922, -0.13479559,  1.61920634,  0.14813252, -0.692845  ,
        0.82986357, -0.31159765, -1.30598178, -1.7711195 , -0.0741648 ])

In [11]:
np.maximum(A, B)

array([ 0.67662148,  0.88197108,  2.30415429,  0.50115688, -0.01192275,
        0.81375717, -0.13006486, -0.07711241, -0.13446684,  0.60980092])

In [14]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True